# Generated by Django 6.0.4 on 2026-05-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parking_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.TextField(default='Not Available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking',
            name='total_slots',
            field=models.IntegerField(default=50),
        ),
    ]
