# Generated by Django 6.0.4 on 2026-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_booking_hours_remove_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='total_slots',
            field=models.IntegerField(),
        ),
    ]
