# Generated by Django 6.0.4 on 2026-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
