# Generated by Django 6.0.4 on 2026-05-08 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_hours_booking_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
    ]
