# Generated by Django 6.0.4 on 2026-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_parking_price_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='price_per_hour',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20),
        ),
    ]
