# Generated by Django 6.0.4 on 2026-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_price_per_hour_parking_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='total_slots',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
