# Generated by Django 6.0.4 on 2026-05-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_payment_id_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
