# Generated by Django 6.0.4 on 2026-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_booking_payment_method_alter_booking_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='RAZORPAY', max_length=50),
        ),
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per hour'),
        ),
    ]
